name: Test it
favicon: null
layout_spectrum: 0.13898402848280966
typography_spectrum: 0
title: Foo Photos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#331d55'
    - '#2d4eec'
    - '#dcc999'
    - '#4d00ff'
    - '#dd6155'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
